### ISSUE TITLE
Potential license incompatibility

### ISSUE THREAD

**Issue by metamoof** [EdiNation/OpenEDI-Specification#2]
Hi,

I'm evaluating your format for use in our company, and I'm wondering if there's a potential license problem. Section 6 of the apache licence specifically states that you do not allow use of trademarks, but at the same time, your format specifically uses your trademark in all the object keys, specifically `x-edination-`.

It would probably be useful for you to explicitly allow the use of the `edination` trademark in code derived from this specification in your license grant or README. 

Alternatively, replacing `x-edination` with `x-openedi` in a new version of the standard would also solve this problem (if openedi isn't trademarked)

**Comment by EdiNation** [comment]
Hi,

Thank you for your comment. We have already planned to change the keys hopefully by the end of the year, from x-edination to x-openedi. Fortunately, OpenEDI isn't trademarked, so it's a nice suggestion.

**Comment by EdiNation** [comment]
Hi,

Version 2.0 has all the keys renamed to x-openedi. Hope it helps.
